spring:
  datasource:
    username: recipes_user
    url: jdbc:mysql://recipes-api-db.mysql.database.azure.com:3306/recipe_assignment
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 'Admin@123$'
  jpa:
    mysql:
      ddl-auto: update
      show-sql: 'true'
    hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
server:
   port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
        